/**
 * Formats diagnostic result into a clean, professional Markdown report
 */
export function formatDiagnosticReport(diagnosis, rawError) {
  if (!diagnosis) return '';

  const solutionsMd = (diagnosis.solutions || [])
    .map(s => `### Step ${s.step}: ${s.title}\n${s.description}\n\n\`\`\`${s.language || 'bash'}\n${s.code}\n\`\`\``)
    .join('\n\n');

  return `# Error Diagnostic Report: ${diagnosis.title || 'Error Analysis'}
**Generated by ErrorLens AI** | ${new Date().toLocaleString()}

- **Detected Runtime / Framework:** ${diagnosis.detectedLanguage || 'General'}
- **Error Code:** \`${diagnosis.errorCode || 'UNKNOWN'}\`
- **Severity Level:** ${diagnosis.severity?.toUpperCase() || 'MEDIUM'}

---

## 1. What Happened
${diagnosis.whatHappened}

## 2. Why It Occurred (Root Cause Analysis)
${diagnosis.whyItOccurred}

## 3. Step-by-Step Fixes
${solutionsMd}

## 4. Prevention & Best Practices
${diagnosis.prevention}

---

### Original Error Trace
\`\`\`
${rawError}
\`\`\`
`;
}

export function downloadMarkdownFile(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
